<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Task List </title>

    <style>
        body {
            padding-left: 40px;
        }
        .content {
            width: 80%;
            margin-left: auto;
            margin-right: auto;
        }
        h1 {
            display: block;
            width: 100%;
            text-align: center;
            margin: 20px;
            font-size: 32px;
        }
        table {
            width: 100%;
            border: 1px solid #000;
            margin-bottom: 20px;
        }
        td, th {
            padding: 10px 20px;
            border: 1px solid #ddd;
        }
        table .user {
            width: 200px;
        }
        textarea {
            width: 99%;
            height: 110px;
        }
        .error_message {
            color: brown;
            font-weight: 600;
        }
        .message {
            color: green;
        }
        .redact {
            float: right;
            margin-top: 40px;
        }
        .new_order {
            margin-top: 100px;
        }
        select {
            margin-top: 20px;
        }
        .page_active {
            background: #1df3ff;
        }
    </style>
</head>
<body>
<div class="content">
    <? if ($error_message):?>
    <? foreach ($error_message as $item) : ?>
            <h1 class="error_message"><? echo $item; ?></h1>
    <? endforeach; ?>
    <? else: ?>
<p>
        <? if ($admin): ?>
            <a href="<? echo APP_WEB_PAGE; ?>/out">Out</a>
        <? else: ?>
        <a href="<? echo APP_WEB_PAGE; ?>/login">Login</a>
        <? endif; ?>
</p>
<? if ($message):?>
    <p class="message">задача записана</p>
<? endif; ?>
<table>
    <tr>
        <th>
            id
        </th>
        <th>
            user
        </th>
        <th>
            description
        </th>
        <th>
            status
        </th>
    </tr>


<?

// выводим сообщения если они есть
if ($taskList) {
    $sizemess = sizeof($taskList);

    $nextId =  $taskList[0]['id'];;

    foreach ($taskList as $item) {


        $taskId = $item['id'];
        $userName = $item['user_name'];
        $email = $item['email'];
        $description = $item['description'];
        $status = $item['status'];
        $redact = $item['redact'];

        if ($redact == 1) {
            $redactTxt = '<hr> отредактировано администратором';
        } else {
            $redactTxt = '';
        }

        if ($admin) {
            $ready_checked[$taskId][$status] = 'checked';

            $status = "<input type='radio' name='status' value='0' {$ready_checked[$taskId][0]} /> no ready <br>
                      <input type='radio' name='status' value='1' {$ready_checked[$taskId][1]}/> ready";

            $description = "<textarea name='description'>$description</textarea>";

            $save = "<input class='redact' type='submit' value='SAVE' />";

        } else {
            if ($status == 1) {
                $status = 'выполнено';
            } else {
                $status = '';
            }
        }

        echo "<tr>
                    <td>
                    <form method='post'>
                        <input type='hidden' name='id' value='$taskId' />
                        <input type='hidden' name='user_name' value='$userName' />
                        <input type='hidden' name='email' value='$email' />
                        
                        $taskId
                    </td>
                    <td class='user'>
                        name: $userName <hr>
                        email: $email
                    </td>
                    <td>
                        $description
                        <br> $redactTxt
                    </td>
                    <td class='status'>
                    
                        $status
                        <br>
                        $save
                        </form>
                    </td>
                </tr>";
    }
}
?>
</table>

<? if ($taskList && $paginate['totalCount'] > $count): ?>

    <form action="" method="post">

        <input type="hidden" name="thisPage" value="<? echo $thisPage; ?>" checked >

        <? if(($sort_by == 'ASC' && $thisPage != 0) || ($sort_by == 'DESC' && $thisPage != 0)): ?>
            <button type="submit" name="next" value="0" > << </button>
        <? endif; ?>

        <? for($x = 0; $x < $paginate['pages']; $x++) : ?>

            <button type="submit" class="pages <? echo $paginate['this_class'][$x]; ?>" name="next" value="<? echo $x; ?>" > <? echo $x + 1; ?>  </button>

        <? endfor; ?>

        <? if(($sort_by == 'ASC' && $thisPage != $x - 1) || ($sort_by == 'DESC' && $thisPage != $x - 1)): ?>
            <button type="submit" name="next" value="<? echo $paginate['pages'] - 1; ?>" > >> </button>
        <? endif; ?>

        <br>

        <select name="sort_name" >
            <?php $selected[$sort_name] = 'selected';
              $sortBy[$sort_by] = 'checked';
            ?>

            <option value="id" <? echo $selected['id']; ?> >default</option>
            <option value="user_name" <? echo $selected['user_name']; ?> >name user</option>
            <option value="email" <? echo $selected['email']; ?> >email</option><option value="status" <? echo $selected['status']; ?> >status</option>
        </select>

        сортировать
        <input type="radio" name="sort_by" value="ASC" <? echo $sortBy['ASC']; ?> > по возрастанию
        <input type="radio" name="sort_by" value="DESC" <? echo $sortBy['DESC']; ?> > по убыванию

        <button type="submit" name="sort" > sort </button>

    </form>

<? endif; ?>

    <div class="new_order">
    <p>Add task</p>
    <form  method="post" >
        <table class="new-task">
        <tr>
            <td>
                <p>Name: </p>
                <input type="text" name="user_name">
            </td>
            <td>
                <p>Email:</p>
                <input type="text" name="email">
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <p> Task </p>
                <textarea name="description" ></textarea> <br> <br>

                <input type="submit" value="SAVE" >
            </td>
        </tr>

        </table>
    </form>
 </div>

<? endif; ?>
</div>
</body>
</html>
